### ISSUE TITLE
golangci had Internal Error after pull request analysis

### ISSUE THREAD

**Issue by yutongp** [golangci/golangci#16]
Please see:
https://golangci.com/r/github.com/iotexproject/iotex-core/pulls/67

This issue is reproducible on our end. We always have this error if we re-trigger golangci with the same pr

**Comment by jirfag** [comment]
Hi!
Sorry for the late response and inconvenient experience. Thank you for reporting!
The pr from the issue is closed now. We've fixed some issues occurring in your newer pull requests, now they are ok.

For your active pull requests:
- https://golangci.com/r/github.com/iotexproject/iotex-core/pulls/83 - no issues
- https://golangci.com/r/github.com/iotexproject/iotex-core/pulls/85 - no issues
- https://golangci.com/r/github.com/iotexproject/iotex-core/pulls/86 - no issues
