### ISSUE TITLE
GolangCI — can't run golangci-lint

### ISSUE THREAD

**Issue by fsamin** [golangci/golangci#23]
Hi,
We have this issue for about 3 days. How can we help you to fix it ?

![screen shot 2018-11-09 at 11 01 50](https://user-images.githubusercontent.com/684151/48256996-84e55880-e411-11e8-9186-29edafc0792f.png)

**Comment by jirfag** [comment]
Hi!
Sorry, we've had temporary issues because of migration to a new version of golangci-lint: it uses go/packages for program analysis and it works differently because of that.

Now everything is fixed, check it please. Also we've added more debug information into these warnings and errors, you can see it [there](https://golangci.com/r/github.com/ovh/cds/pulls/3571).

To fully mitigate errors on your repo, as I understand, we need to run a custom command before analysis to generate some code. An ability to run custom commands in planned in 1-4 weeks.

**Comment by bnjjj** [comment]
Thanks for your fix, the warnings on our project are coming from an error on our side :) we will fix it.

**Comment by fsamin** [comment]
@jirfag all is fine now on our side
thanks for all of these, that's really a great tool
