### ISSUE TITLE
Analysis fails with imported packages - no Go Files in

### ISSUE THREAD

**Issue by lucabrasi83** [golangci/golangci#29]
Hi,

I'm facing similar issue described in #24  with `no Go Files in` errors for imported packages.

My workaround is to skip these directories in .golangci.yml file but I was wondering whether there is any better solution:

```yaml
skip-dirs:
    - github.com/x-cray/logrus-prefixed-formatter
    - github.com/sirupsen/logrus
    - github.com/speps/go-hashids
    - github.com/shirou/gopsutil/disk
    - github.com/shirou/gopsutil/cpu
    - github.com/shirou/gopsutil/host
    - github.com/shirou/gopsutil/mem
    - github.com/jackc/pgx
    - github.com/appleboy/gin-jwt
    - github.com/docker/docker/api/types
    - github.com/docker/docker/api/types/container
    - github.com/docker/docker/api/types/mount
    - github.com/gin-gonic/gin
    - github.com/gin-gonic/gin/json
    - github.com/go-ini/ini
    - gopkg.in/dgrijalva/jwt-go.v3
    - github.com/docker/docker/client
    - github.com/swaggo/gin-swagger
    - github.com/swaggo/gin-swagger/swaggerFiles
    - github.com/alecthomas/template
    - github.com/swaggo/swag
    - vendor$
```

Thanks & Regards,

**Comment by jirfag** [comment]
Hi!
Sorry for bad error message `no Go Files in`: it means that dependency wasn't loaded.
According to my logs, it looks like the command `GO111MODULE=on go mod tidy` in `prepare` section of `.golangci.yml` breaks build.
We analyze without `GO111MODULE=on` therefore if `prepare` section isn't set we run `GO111MODULE=on go mod vendor` to make a `vendor` dir. In your case because of the custom `prepare` section we didn't run `GO111MODULE=on go mod vendor` and therefore couldn't load dependencies during analysis.
If you would like to run custom commands in `prepare` then just add `GO111MODULE=on go mod vendor` to them.

Also, you can remove `skip-dirs`: it shouldn't help with this problem.

**Comment by lucabrasi83** [comment]
Thanks @jirfag . I've tried as suggested and didn't get any error.

**Comment by jirfag** [comment]
feel free to contact us if you have any issues!
