### ISSUE TITLE
"Can't activate repo" when trying to add GolangCI

### ISSUE THREAD

**Issue by adamdecaf** [golangci/golangci#3]
Hey! This seems like a cool project so I wanted to try it out. I'm trying to setup [adamdecaf/cert-manage](https://github.com/adamdecaf/cert-manage) with this, but running into an issue.

I'm using my bot account (@adamdecaf-bot) and getting "Can't activate repo" when clicking "Connect". I assume this is due to permissions on my bot account and repo? 

<div style="text-align:center; width:100%;" ><img width="364" alt="screen shot 2018-03-10 at 2 55 40 pm" src="https://user-images.githubusercontent.com/120951/37247671-ac4ffc8a-2473-11e8-8b3f-b17a9ba60e03.png"></div>

I searched the code a bit and found [the error message](https://github.com/golangci/golangci-api/blob/72a6483b710672a2bf60297186c6760112bf10bc/app/handlers/repos/activate.go#L28), but it looks like the underlying error isn't reported to the user.

**Comment by golangci** [comment]
Hello!
Thank you for report and investigation. You are right: it's an issue due to permissions.
1.  Repo [cert-manage](https://github.com/adamdecaf/cert-manage) is created in user-level account, not organization-level. It means that this repo can have only 1 owner (admin): it's user **adamdecaf**. You just need to sign in with this user to [GolangCI](https://golangci.com).
2. We've fixed this incomprehensible error: now we check repo permissions and don't show repo activation button in such cases but show text `Only repo admins can connect repo`.

**Comment by adamdecaf** [comment]
Oh. What permissions does an owner have the other contributors couldn't have? Is there something on Github's side that prevents contributors from adding bots?

**Comment by golangci** [comment]
Our service installs webhook to subscribe to new pull requests. Collaborators have [a lot of permissions](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) but [can't install webhooks](https://help.github.com/articles/about-webhooks/) :(

**Comment by adamdecaf** [comment]
Ah, ok. Thanks!
